# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :hybrid do
    cocoapods(use_bundle_exec: false)
    api_key = app_store_connect_api_key(
    			key_id: 'GZ9TM4Z4PC',
			issuer_id: '69a6de87-1049-47e3-e053-5b8c7c11a4d1',
			key_filepath: 'AuthKey_GZ9TM4Z4PC.p8'
		)
    build_app(workspace: "HybridFrame.xcworkspace", scheme: "hybrid")
    upload_to_testflight(
			api_key: api_key
    )
  end
end