name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: ios
    
    env:
      XC_VERSION: ${{ '13.2.1' }}
      XC_PROJECT: ${{ 'HybridFrame.xcworkspace' }}
      XC_SCHEME: ${{ 'hybrid' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit tests
        run: |
          xcodebuild test -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 13'
